[package]
name = "dirtytype"
version = "0.1.0"
edition = "2021"
description = "A marker of types being dirty for Rust"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
